pipeline {
    agent any
    stages {
        stage ('job1') {
            steps {
                    sh "echo 'Building Job1'"
                    build job: 'job1'
            }
        }
        stage ('job2') {
            steps {
                    sh "echo 'Building Job1'"
                    build job: 'job2'
                    
            }
        }
        stage ('job3') {
            steps {
                    sh "echo 'Building Job with spaces'"
                    build job: 'with spaces'
                    
            }
        }
    }
    post {
     success {
       sh "echo 'helm job'"
       build job: 'helm'
     }
   }
}
